[serve]
# The address to serve on LAN.
addresses = ["0.0.0.0"]
# The address to serve on WAN.
# address = "0.0.0.0"
# The port to serve on.
port = 8000
headers = { "X-Content-Type-Options" = "nosniff" }

[[proxy]]
rewrite = "/api/v1/"
backend = "http://localhost:9000/"
# backend = "http://localhost:9000/"

[build]
no_sri = true
target = "index.html"       # The index HTML file to drive the bundling process.
html_output = "index.html"  # The name of the output HTML file.
# release = true             # Build in release mode.
